# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Title', models.TextField(max_length=500)),
                ('Video_Description', models.TextField(max_length=500)),
                ('Video_Categorization', models.CharField(max_length=30)),
                ('Video_Date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('video_is_deleted', models.BooleanField(default=False, verbose_name='\u0647\u0644 \u0627\u0644\u0641\u062f\u064a\u0648 \u0645\u062d\u0630\u0648\u0641\u061f')),
            ],
        ),
    ]
