# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube',
            old_name='Video_Date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='youtube',
            old_name='Video_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='youtube',
            old_name='Video_Title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='youtube',
            old_name='video_is_deleted',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='Video_Categorization',
        ),
        migrations.AddField(
            model_name='youtube',
            name='Categorization',
            field=models.CharField(choices=[('B', 'biology'), ('M', 'microbiology')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtube',
            name='link',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtube',
            name='uploadedby',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
