# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20180618_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=250)),
                ('Description', models.TextField(max_length=350)),
                ('Categorization', models.CharField(choices=[('B', 'biology'), ('M', 'microbiology')], max_length=1)),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='\u0647\u0644 \u0627\u0644\u0642\u0646\u0627\u0629 \u0645\u062d\u0630\u0648\u0641\u061f')),
                ('link', models.TextField(max_length=100)),
                ('uploadedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='youtube',
            name='link',
            field=models.TextField(max_length=100),
        ),
    ]
