# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180619_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='telegram',
            new_name='telegram_model',
        ),
    ]
