# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180620_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegram_model',
            name='Categorization',
            field=models.CharField(choices=[('B', 'biology'), ('M', 'microbiology'), ('P', 'physiology')], max_length=1),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='Categorization',
            field=models.CharField(choices=[('B', 'biology'), ('M', 'microbiology'), ('P', 'physiology')], max_length=1),
        ),
    ]
