# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_auto_20180623_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='fresheyes_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=75)),
                ('Description', models.TextField(max_length=150)),
                ('Categorization', models.CharField(choices=[('B', 'biology'), ('M', 'microbiology'), ('P', 'physiology')], max_length=1)),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='\u0647\u0644 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u0645\u062d\u0630\u0648\u0641\u061f')),
                ('file', models.FileField(upload_to=b'')),
                ('uploadedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='telegram_model',
            name='Description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='telegram_model',
            name='Title',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='Description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='Title',
            field=models.TextField(max_length=75),
        ),
    ]
