# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20180628_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
            ],
        ),
        migrations.AlterField(
            model_name='fresheyes_model',
            name='Categorization',
            field=models.CharField(choices=[('', '--'), ('B', 'biology'), ('M', 'microbiology'), ('P', 'physiology')], max_length=1),
        ),
        migrations.AlterField(
            model_name='telegram_model',
            name='Categorization',
            field=models.CharField(choices=[('', '--'), ('B', 'biology'), ('M', 'microbiology'), ('P', 'physiology')], max_length=1),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='Categorization',
            field=models.CharField(choices=[('', '--'), ('B', 'biology'), ('M', 'microbiology'), ('P', 'physiology')], max_length=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.post'),
        ),
    ]
