# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0008_auto_20180708_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='fresheyes_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=150)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='\u0647\u0644 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u0645\u062d\u0630\u0648\u0641\u061f')),
                ('file', models.FileField(blank=True, null=True, upload_to='Fresh_eyes/comment/')),
            ],
        ),
        migrations.CreateModel(
            name='fresheyes_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=75)),
                ('Description', models.TextField(max_length=150)),
                ('Categorization', models.CharField(choices=[('', '--'), ('B', 'biology'), ('M', 'microbiology'), ('P', 'physiology')], max_length=1)),
                ('Date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='\u0647\u0644 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u0645\u062d\u0630\u0648\u0641\u061f')),
                ('file', models.FileField(blank=True, null=True, upload_to='Fresh_eyes/')),
                ('uploadedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='fresheyes_model',
            name='uploadedby',
        ),
        migrations.DeleteModel(
            name='fresheyes_model',
        ),
        migrations.AddField(
            model_name='fresheyes_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.fresheyes_post'),
        ),
    ]
