# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180708_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fresheyes_post',
            name='Description',
        ),
        migrations.AddField(
            model_name='fresheyes_post',
            name='help_type',
            field=models.TextField(default=True, max_length=150, verbose_name='\u0646\u0648\u0639 \u0627\u0644\u0645\u0633\u0627\u0639\u062f\u0629\u061f'),
        ),
    ]
