# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180710_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_name', models.CharField(max_length=50)),
                ('is_blocker', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Description',
            field=models.TextField(default=True, max_length=150),
            preserve_default=False,
        ),
    ]
