# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20180720_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
