# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='\u0647\u0644 \u0627\u0644\u062a\u0639\u0644\u064a\u0642 \u0645\u062d\u0630\u0648\u0641\u061f'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='\u0647\u0644 \u0627\u0644\u0645\u0642\u0627\u0644 \u0645\u062d\u0630\u0648\u0641\u061f'),
        ),
    ]
